server:
  port: 9010

application:
  name: Communication Management service
  description: API created to manage email notifications

spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: canelabank@gmail.com
      password: qmippwdhmjtcyukd
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
